server:
  port: 10010
spring:
  application:
    name: gateway  # jdk修改为1.8可以运行
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos地址
    gateway:
      routes:
        - id: user-service #路由标识必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates:   # 路由断言 判断请求是否符号标准
            - Path=/user/**  # 路径断言，判断路径是否以/user开头，是就符号规则
#          filters:
#            - AddRequestHeader=Truth, sb #过滤器，其中的逗号是等于的意思，添加响应头，需要在controller中添加参数
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
        #    - After  #时间
      default-filters:   #全局过滤器
        - AddRequestHeader=Truth, sb #过滤器，其中的逗号是等于的意思，添加响应头，需要在controller中添加参数