server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-order?useSSL=false&allowPublicKeyRetrieval=True
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
      name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址
      discovery:
        cluster-name: HZ  #选择集群
      #  namespace: 8c9a49f2-2782-427a-adde-a4227657c5db #命名空间id ,这里是新建的命名空间目前删除了
        ephemeral: false #非临时实例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # Eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
#负载均衡修改
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule #阿里巴巴的集群负载均衡
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #普通的随机负载均衡
ribbon:
  eager-load:
    clients: userservice #饥饿加载
    enabled: true
feign:
  httpclient:
    enabled: true #支持HTTPClient的开关
    max-connections: 200 #最大连接数
    max-connections-per-route: 50   #单个路径的最大连接数
#  client:
#    config:
#      default:        #是否全局，default是全局，
#        logger-level: Full #级别


